config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  post 'books'=>'books#create'
  get 'books' => 'books#index'
  get 'books/:id'=>'books#show', as: 'book'
  get 'books/:id/edit'=>'books#edit', as: 'edit_book'
  patch 'books/:id'=>'books#update', as: 'update_book'
  delete 'books/:id'=>'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book=Book.new(book_params)
    @books = Book.all
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @books=Book.find(params[:id])
  end

  def edit
    @books=Book.find(params[:id])
  end

  def update
    @books = Book.find(params[:id])
  if @books.update(book_params)
    flash.now[:success] = "Book was successfully updated."
    render :edit
  else
    flash.now[:error] = "#{@books.errors.count} error prohibited this book from being saved:"
    flash.now[:error_message] = @books.errors.full_messages.to_sentence
    render :edit
  end
end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    #topアクションの実装
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<% if flash[:success].present? %>
  <p><%= flash[:success] %></p>
<% end %>

<% if flash[:error].present? %>
  <p><%= flash[:error] %></p>
  <p><%= flash[:error_message] %></p>
<% end %>

<h1>Editing Book</h1>
<%= form_with model: @books, url: update_book_path(@books.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Books' %>

   <%= link_to "Show", book_path(@books.id) %> | <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
  <h1>Books</h1>
  <table>
   <thead>
    <tr>
     <th>Title</th>
     <th>Body</th>
     <th></th>
     <th></th>
     <th></th>
     </tr>
   </thead>
   <tbody>
   <% @books.each do |book| %>
   <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
  <td><%= link_to "Show", book_path(book.id) %></td>
  <td><%= link_to "Edit", edit_book_path(book.id) %></td>
  <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
  <% end %>
  </tbody>
  </table>

   <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this book from being saved:
     <ul>
       <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   <% end %>

   <%= form_with model: @books,url: '/books',methood: :post do |f| %>
     <h4>Title</h4>
     <%= f.text_field :title %>

     <h4>Body</h4>
     <%= f.text_area :body %>

     <%= f.submit 'Create Book' %>
   <% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<h2>Title:</h2>
<p><%= @books.title %></p>

<h2>Body:</h2>
<p><%= @books.body %></p>

<%= link_to "Edit", edit_book_path(@books.id) %> | <%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="homes.scss" />
    <title>BookersApp</title>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong> へ！</h1>
    <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
    <p><%= link_to "Start", books_path %></p>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
      <%= yield %>
  </body>
</html>